# Rocket parameters
stages: 4
diameters:
  - 0
  - 0.156 
  - 0.156 
  - 0.135
stage_z: 
  - 0 
  - 0.242 
  - 4.11 
  - 4.16 
fin_n: 3
fin_top_offset: 3.83 
fin_span: 0.2
fin_root_chord: 0.28 # base length
fin_tip_chord: 0.125
fin_sweep: 0.1071e-3
fin_thickness: 0.004
lug_n: 2
lug_S: 5.7e-4 
dry_mass: 41.558
dry_CM: 2.14
dry_I:
  - 47
  - 47
  - 2
propellant_mass: 6 #3.693
propellant_CM: 3
Isp: 213
maxThrust:
  - 200
  - 200
  - 2400
minThrust: 
  - -200
  - -200
  - 0
Cd:
  - 2
  - 2
  - 0.7